
matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: "10"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      services: docker
      language: generic

before_script:
  - docker pull nampdn/puskerit:latest
  - pwd
  - ls -las
  - docker build -t vietbible/desktop --build-arg GIT_REPO=$GIT_REPO,SSH_PRIVATE_KEY=$SSH_PRIVATE_KEY .
script:
    - docker run --rm vietbible/desktop -e GIT_REPO="git@github.com:vgmtv/vietbible.git" /bin/sh -c "git clone $GIT_REPO"
  - docker run --rm vietbible/desktop -e GIT_REPO="$GIT_REPO" /bin/sh -c "git clone $GIT_REPO"
